security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Liverpool\tiendaBundle\Entity\User: plaintext
        
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    
    providers:
        chain_provider:
            chain:
                providers: [in_memory, our_db_provider]
        in_memory:
            memory:
                users:
                    admin: { password: tuchito1, roles: ROLE_ADMIN }
        our_db_provider:
            entity: { class: LiverpooltiendaBundle:User, property: usuario }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true
    
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: /createUser*, roles: ROLE_ADMIN}
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY}
