categoria_index:
    path:     /
    defaults: { _controller: "LiverpooltiendaBundle:Categoria:index" }
    methods:  GET

categoria_show:
    path:     /{id}/show
    defaults: { _controller: "LiverpooltiendaBundle:Categoria:show" }
    methods:  GET

categoria_new:
    path:     /new
    defaults: { _controller: "LiverpooltiendaBundle:Categoria:new" }
    methods:  [GET, POST]

categoria_edit:
    path:     /{id}/edit
    defaults: { _controller: "LiverpooltiendaBundle:Categoria:edit" }
    methods:  [GET, POST]

categoria_delete:
    path:     /{id}/delete
    defaults: { _controller: "LiverpooltiendaBundle:Categoria:delete" }
    methods:  DELETE
